Databrew Pipeline Example
aws-samples/aws-ddk-examples pull request #35
Opened 2023-03-29 15:26 UTC by b-akhil

*Issue #, if available:* **Not applicable**

*Description of changes:* Added a Example Databrew Pipeline which leverages the DDK DataBrewFactory and DataBrewTransformStage.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-29 23:23 UTC, malachi-constant reviewed
I was able to test a deployment and invocation and everything worked great! Thanks so much for the contribution.

2023-03-30 04:34 UTC, b-akhil commented on databrew-athena/app.py
> +DdkApplicationStack(app, "DdkApplicationStack", "dev")
Understood, Let me make the changes

2023-03-30 10:25 UTC, b-akhil commented on databrew-athena/app.py
> +DdkApplicationStack(app, "DdkApplicationStack", "dev")
I have changed the stack name from `DdkApplicationStack` to  `DataBrewAthenaStack`. I also changed the file name.

Also made one another change with custom resource lambda handler for the deleting the recipe.

2023-03-30 17:34 UTC, malachi-constant approved these changes

2023-03-30 19:13 UTC, anmolsgandhi requested changes
Looks Good !! Left some minor comments

2023-03-30 19:13 UTC, anmolsgandhi commented on databrew-athena/ddk_app/databrew_athena_stack.py
can you remove unused imports ?

2023-03-31 12:05 UTC, b-akhil commented on databrew-athena/ddk.json
Removed the configs within ddk.json as they are not being used

2023-03-31 12:06 UTC, b-akhil commented on databrew-athena/requirements.txt
Updated the DDK Version to 0.6.2

2023-03-31 12:06 UTC, b-akhil commented on databrew-athena/ddk_app/databrew_athena_stack.py
Removed the unused imports within databrew_athena_stack.py

2023-03-31 12:36 UTC, anmolsgandhi approved these changes

2023-03-31 16:23 UTC, merged